id: gdelt-ingest
namespace: gdelt

triggers:
  - id: schedule
    type: io.kestra.plugin.core.trigger.Schedule
    cron: "*/15 * * * *"

tasks:
  - id: ingest
    type: io.kestra.plugin.scripts.python.Commands
    pythonVersion: "python: 3.12"
    containerImage: gdelt-producer
    taskRunner:
      type: io.kestra.plugin.scripts.runner.docker.Docker
      networkMode: gdelt-net
      pullPolicy: NEVER
    env:
      KAFKA_BOOTSTRAP_SERVERS: redpanda:9092
    commands:
      - python /app/main.py

retry:
  type: constant
  maxAttempt: 3
  interval: PT30S