id: gdelt-ingest
namespace: gdelt

triggers:
  - id: schedule
    type: io.kestra.plugin.core.trigger.Schedule
    cron: "*/15 * * * *"

tasks:
  - id: ingest
    type: io.kestra.plugin.scripts.python.Commands
    runner: DOCKER
    docker:
      image: gdelt-producer
      networkMode: gdelt-net
    env:
      KAFKA_BOOTSTRAP_SERVERS: redpanda:9092
    commands:
      - python /app/main.py

retry:
  type: constant
  maxAttempt: 3
  interval: PT30S
