name: climate
version: "1.0.0"
config-version: 2

profile: climate

model-paths: ["models"]
macro-paths: ["macros"]
seed-paths: ["seeds"]
target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

on-run-start:
  - "{{ create_raw_schema() }}"

seeds:
  climate:
    +schema: seeds
    country_iso_codes:
      +column_types:
        iso2: text
        iso3: text
        wb_code: text
        country_name: text

models:
  climate:
    staging:
      +materialized: view
      +schema: staging
