CREATE TABLE kafka_events (
    `global_event_id`  BIGINT,
    `sql_date`         INT,
    `actor1_code`      STRING,
    `actor1_name`      STRING,
    `actor1_country`   STRING,
    `actor2_code`      STRING,
    `actor2_name`      STRING,
    `actor2_country`   STRING,
    `event_root_code`  STRING,
    `quad_class`       INT,
    `goldstein_scale`  DOUBLE,
    `num_mentions`     INT,
    `num_sources`      INT,
    `num_articles`     INT,
    `action_geo_type`  INT,
    `action_geo_name`  STRING,
    `action_geo_lat`   DOUBLE,
    `action_geo_long`  DOUBLE,
    `date_added`       BIGINT,
    `source_url`       STRING,
    `proc_time` AS PROCTIME()
) WITH (
    'connector'                      = 'kafka',
    'topic'                          = 'gdelt.events',
    'properties.bootstrap.servers'   = '$KAFKA_BROKER',
    'properties.group.id'            = 'flink-event-aggregations',
    'scan.startup.mode'              = 'earliest-offset',
    'format'                         = 'json',
    'json.fail-on-missing-field'     = 'false',
    'json.ignore-parse-errors'       = 'true'
)
