services:
  boc-web:
    build:
      context: .
      args:
        DATABASE_URL: postgresql://${POSTGRES_USER:-root}:${POSTGRES_PASSWORD:-root}@${POSTGRES_HOST}:${POSTGRES_PORT:-5432}/${POSTGRES_DB:-boc}
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER:-root}:${POSTGRES_PASSWORD:-root}@${POSTGRES_HOST}:${POSTGRES_PORT:-5432}/${POSTGRES_DB:-boc}
      NODE_ENV: production
      NEXT_TELEMETRY_DISABLED: "1"
    networks:
      - boc-postgres-network
    restart: always

networks:
  boc-postgres-network:
    name: boc-postgres-network
    external: true
