version: 2

sources:
  - name: raw_data
    description: "Registros sin procesar de los taxis de Nueva York"
    database: nytaxi # Nombre de la base de datos DuckDB
    schema: prod
    freshness:
      warn_after: {count: 24, period: hour}
      error_after: {count: 48, period: hour}
    tables:
      - name: yellow_tripdata
        description: Registros brutos de viajes en taxi amarillo
        loaded_at_field: tpep_pickup_datetime
        columns:
          - name: vendorid
            description: "Proveedor de tecnología de taxi (1: Creative Mobile Technologies, 2: VeriFone Inc.) - Nota: Los datos brutos pueden contener nulls, filtrados en staging"
          - name: tpep_pickup_datetime
            description: Fecha y hora en que el taxímetro fue activado
          - name: tpep_dropoff_datetime
            description: Fecha y hora en que el taxímetro fue desactivado
          - name: passenger_count
            description: Número de pasajeros en el vehículo
          - name: trip_distance
            description: Distancia del viaje en millas
          - name: pulocationid
            description: Zona TLC Taxi donde el taxímetro fue activado
          - name: dolocationid
            description: Zona TLC Taxi donde el taxímetro fue desactivado
          - name: ratecodeid
            description: "Código de tarifa (1: Standard, 2: JFK, 3: Newark, 4: Nassau/Westchester, 5: Negotiated, 6: Group)"
          - name: store_and_fwd_flag
            description: Registro del viaje almacenado en la memoria del vehículo (Y/N)
          - name: payment_type
            description: "Método de pago (1: Credit card, 2: Cash, 3: No charge, 4: Dispute, 5: Unknown, 6: Voided)"
          - name: fare_amount
            description: Tarifa por tiempo y distancia
          - name: extra
            description: Extras y recargos misceláneos
          - name: mta_tax
            description: Impuesto MTA
          - name: tip_amount
            description: Importe de la propina (solo tarjeta de crédito)
          - name: tolls_amount
            description: Total de peajes pagados
          - name: improvement_surcharge
            description: Recargo de mejora
          - name: total_amount
            description: Importe total cobrado
      - name: green_tripdata
        description: Registros brutos de viajes en taxi verde
        loaded_at_field: lpep_pickup_datetime
        columns:
          - name: vendorid
            description: "Proveedor de tecnología de taxi (1: Creative Mobile Technologies, 2: VeriFone Inc.) - Nota: Los datos brutos pueden contener valores nulos que serán filtrados en `staging`"
          - name: lpep_pickup_datetime
            description: Fecha y hora en que el taxímetro fue activado
          - name: lpep_dropoff_datetime
            description: Fecha y hora en que el taxímetro fue desactivado
          - name: passenger_count
            description: Número de pasajeros en el vehículo
          - name: trip_distance
            description: Distancia del viaje en millas
          - name: pulocationid
            description: Zona TLC Taxi donde el taxímetro fue activado
          - name: dolocationid
            description: Zona TLC Taxi donde el taxímetro fue desactivado
          - name: ratecodeid
            description: "Código de tarifa (1: Standard, 2: JFK, 3: Newark, 4: Nassau/Westchester, 5: Negotiated, 6=Group)"
          - name: store_and_fwd_flag
            description: Registro del viaje almacenado en la memoria del vehículo (Y/N)
          - name: payment_type
            description: "Método de pago (1: Credit card, 2: Cash, 3: No charge, 4: Dispute, 5: Unknown, 6: Voided)"
          - name: fare_amount
            description: Tarifa por tiempo y distancia
          - name: extra
            description: Extras y recargos misceláneos
          - name: mta_tax
            description: Impuesto MTA
          - name: tip_amount
            description: Importe de la propina (solo tarjeta de crédito)
          - name: tolls_amount
            description: Total de peajes pagados
          - name: improvement_surcharge
            description: Recargo de mejora
          - name: total_amount
            description: Importe total cobrado
          - name: trip_type
            description: "Tipo de viaje (1: Street-hail, 2: Dispatch)"
          - name: ehail_fee
            description: Tarifa de E-hail
      - name: fhv_tripdata
        description: Raw FHV taxi trip records
        columns:
          - name: dispatching_base_num
            description: The TLC Base License Number of the base that dispatched the trip
          - name: affiliated_base_number
            description: |
              Base number of the base with which the vehicle is affiliated.
              This must be provided even if the affiliated base is the same as the dispatching base.
          - name: pulocationid
            description: TLC Taxi Zone in which the trip began
          - name: dolocationid
            description: TLC Taxi Zone in which the trip ended
          - name: pickup_datetime
            description: The date and time of the trip pick-up
          - name: dropoff_datetime
            description: The date and time of the trip dropoff
          - name: sr_flag
            description: |
              Indicates if the trip was a part of a shared ride chain offered by a High Volume FHV company (e.g. Uber Pool, Lyft Line).
              For shared trips, the value is 1. For non-shared rides, this field is null.