id: schedule_download_current_year
namespace: boc
description: Download the index of bulletins of the current year on a schedule

variables:
  is_not_current_year: "{{ trigger.date | date('yyyy') != now() | date('yyyy') }}"

tasks:
  - id: label
    type: io.kestra.plugin.core.execution.Labels
    labels:
      type: year_bulletins
      year: "{{ trigger.date | date('yyyy') }}"

  - id: if_not_current_year
    type: io.kestra.plugin.core.flow.If
    condition: "{{ render(vars.is_not_current_year) }}"
    then:
      - id: exit
        type: io.kestra.plugin.core.execution.Exit
        state: CANCELED
        description: "Backfills are not supported for this job"

  - id: download
    type: io.kestra.plugin.core.flow.Subflow
    namespace: boc
    flowId: download_years
    inputs:
      year: "{{ trigger.date | date('yyyy') }}"
      overwrite: true

triggers:
  - id: daily_schedule
    type: io.kestra.plugin.core.trigger.Schedule
    description: Once a day
    cron: "0 0 * * *"
